export const BASE_URL = '/home2'
export const NEW_EVENT_URL = BASE_URL + '/new-event'
export const PUBLIC_EVENTS_URL = BASE_URL + '/public-events'
export const MY_EVENTS_URL = BASE_URL + '/my-events'
export const VIEW_EVENT_URL = '/view/events/'
export const MANAGE_EVENT_URL = '/manage/'
